- Makefile.am
- test-init.sh
- tests/check-core.c
This fixes the make check issues I can into on Clear Linux. Plus changes out Werror because it has outlived its usefulness.
The tests still fail by default though because of timeouts. This is caused by a lot of syncs being done in the purge test. I'm considering how to best make the syncs no ops in the check tests and while the best way is likely a dlopen and replace kind of workflow it may be a little much when we could just add a compile flag for check builds that causes sync to be replaced.
I'm open to ideas on that last point though.
> Check fixes

- src/bootloaders/syslinux.c
Instead of using whatever extlinux is in the path, explicitly only use
the target extlinux command to avoid issues with older versions not
supporting the install or update use cases.
> Use the target's extlinux

- src/nica/util.c
The only sockets held are irrelevant for our file descriptor
leak check, which focuses on leaks in opening/closing regular
files. Some of the sockets are things like pacrunner that
curl opens, and we should just ignore leaks in them.
Copied from my change in swupd-client v3.6.5
> Ignore leaks in sockets.

- src/bootloaders/syslinux.c
- src/bootloaders/systemd-class.c
- src/bootman/kernel.c
This implements issue #31 and unblocks the next release, by only updating target assets, such
as kernel blobs and bootloader text configurations, when they really need updating.
> Write when change

- src/bootman/files.c
This one is a real simple fix. Basically I was getting issues with the autoupgrade test suite with `check-valgrind` (reachable, conditional jumps, etc) due to the `file_get_text` function.
> bootman/files: Fix problematic file_get_text function

- .travis.yml
- Makefile.am
- Switch tree to using GCC 5 (vs GCC 4.8.0 ...)
- Include updated Nica which has switched to C11
- Enable C11 by default
- Fix derp in makefile
- Underp ordering of travis dependencies
> Travis GCC5/C11

- Makefile.am
- src/bootloaders/syslinux.c
- src/bootloaders/systemd-class.c
- src/bootman/bootman.h
- src/bootman/kernel.c
- src/lib/writer.c
- src/lib/writer.h
- tests/check-core.c
- tests/harness.c
Note this is simply initial initrd support so that the plumbing is in place.
Due to some broken assumptions from the older life of CBM, it prevents "nicely" adding full support for issue #25. A probing method will need to be added to handle GPT vs MBR (PartUUID vs UUID.)
So for now this just adds initrd support to *existing* bootloaders. Should ideally be merged after a new tag for the existing tree so that this can target 2.0
Also note the introduction of simpler string/asprint management to make life easier.
> Add initial initrd support

- continous.sh
- docker/Dockerfile
- docker/dockerrun.sh
In order to assist in building up test coverage, we need to do so in a way
that allows to test dangerous changes locally. Emulating an environment that
has no /sys or /dev is absurdly difficult.
Instead, we add a method to enable building (reproducibly) within a Docker
image based on Clear Linux. The build will take a full snapshot of the
current tree from a *read-only* bind mount into the target tree. At this
point it will attempt all parts of the normal Travis build steps, and will
ultimately emit the contents of the build log should failures be encountered.
Additionally we have the added benefit of working with a modern toolchain,
as opposed to the very old offerings on Travis.
> Add support for automated building within docker environment.

- Makefile.am
- compat/README.md
- compat/gummiboot_updaters.sh
- compat/kernel_updater.sh
- compat/systemdboot_updater.sh
- configure.ac
These scripts were originally needed when transitioning to clr-boot-manager
within Clear Linux. However, they will no longer be invoked by swupd-client
due to clearlinux/swupd-client#179 so we will now remove them "at source".
P.S. This also means this change can only be released in 2.0 and not before.
> Remove the compatibility scripts

- src/bootloaders/syslinux.c
This change corrects a bug found in the coverage testing, whereby the wrong
item was freed (The modified pointer, not the original copy pointer.)
> bootloader/syslinux: Fix nasty segfault

- Makefile.am
- src/bootloaders/syslinux.c
- src/bootloaders/systemd-class.c
- src/bootman/bootman.c
- src/bootman/kernel.c
- src/bootman/timeout.c
- src/cli/ops/report_booted.c
- src/lib/cmdline.c
- src/lib/files.c
- src/lib/os-release.c
- src/lib/probe.c
- src/lib/system_stub.c
- src/lib/util.c
- src/lib/util.h
- tests/check-legacy.c
- tests/check-uefi.c
- tests/harness.c
- tests/system-harness.h
This change should raise the coverage up almost 2%, by adding a new `util.c`, with a `string_printf` helper to remove all the `if !string; abort` flow.
I also un-inlined `rstrip` as it made no sense to be inlined. Most importantly, this change makes the code easier to follow.
> asprintf based coverage helping

- Makefile.am
- src/bootloaders/bootloader.h
- src/bootloaders/goofiboot.c
- src/bootloaders/gummiboot.c
- src/bootloaders/syslinux.c
- src/bootloaders/systemd-boot.c
- src/bootloaders/systemd-class.c
- src/bootloaders/systemd-class.h
- src/bootman/bootman.c
- src/bootman/bootman.h
- src/bootman/kernel.c
- src/bootman/update.c
- src/lib/cmdline.c
- src/lib/files.c
- src/lib/log.c
So I started this branch with the intent of enabling secure boot but got distracted by some
obvious things that gcc was missing (unused autofrees) - so after the caps were added I
set about cleaning those up.
Anyway, I need the capability stuff in for the secure boot bits too, as I'll want to ask the bootloader if its UEFI, then prefix the paths with `EFI/` and do the migration bits. I suspect the coverage is gonna drop a half percent here, apologies. I'll make it back up in the next change hopefully, though I need migration & inclusion of sboot bits..
> Cleanup & capabilities

- .gitignore
- Makefile.am
- README.md
- src/bootloaders/grub2.c
- src/bootman/bootman.c
- src/bootman/bootman.h
- src/bootman/kernel.c
- src/bootman/sysconfig.c
- src/bootman/update.c
- src/cli/main.c
- src/lib/files.c
- src/lib/os-release.c
- tests/check-grub2.c
This (long awaited) PR adds GRUB2 loader support.
This is used when no other bootloader is found to be compatible, i.e. non GPT non UEFI systems.
Additionally we add some minor cleanups and documentation around CBM integration
The GRUB2 code has been tested by (at the time of unwriting) 4 Solus users and shown to be working with:
- Encrypted LVM
- "Standard" (no encryption) install
- Separate /boot and non-separate /boot
> Add GRUB2 support

- .gitignore
- Makefile.am
- src/bootman/bootman.c
- src/bootman/bootman.h
- src/bootman/sysconfig.c
- tests/check-select-bootloader.c
This helps with issue #54, and after roughly 40 test ISOs, and users testing chroot'd installs, we're now back to defaulting UEFI, and GRUB2 is a highly specialist configuration (!image, !uefi, !legacy|syslinux)
Confirmed my installer works now, and things are dandy. Fixed a couple of bugs along the way when dealing with a `/boot/efi` -> `/boot` transition for chroot tests.
> Chroot improvements

- .gitignore
- Makefile.am
- src/lib/blkid_stub.c
- src/lib/blkid_stub.h
- src/lib/probe.c
- src/lib/probe.h
- tests/blkid-harness.h
- tests/check-probe.c
- tests/check-select-bootloader.c
- tests/harness.c
We add a new test & probe changes to support explicit GPT detection so that we know when to use PartUUID and when to use UUID, resolving #53
> probe: Add support to determine if a device uses a GPT table or not

- src/bootman/sysconfig.c
- tests/check-select-bootloader.c
Fixes this issue: https://solus-project.com/forums/viewtopic.php?t=7129&p=20529#p20523
> bootman: Allow native UEFI to "win" on GPT system containing legacy boot

- src/bootloaders/grub2.c
- src/bootloaders/syslinux.c
- src/bootman/kernel.c
- tests/check-grub2.c
This change allows CBM to dynamically use submenus, via a single GRUB2 config file
When only one kernel is known, a normal menu is used. Likewise, we do the same for the default kernel.
Anything else then lives in a submenu for alternative boot entries
Additionally this change fixes syslinux emitting duplicated entries when old kernels are retained.
> Grub submenus

- src/lib/blkid_stub.c
- src/lib/files.c
- src/lib/probe.c
- src/lib/system_stub.c
- tests/check-legacy.c
- tests/check-probe.c
- tests/check-select-bootloader.c
As of glibc 2.25, warnings will be emitted at compile time to state
that you must explicitly include the header now, due to libraries
tending to have their own definitions.
> Ensure to include sysmacros.h for major/minor usage

- src/bootman/kernel.c
- tests/check-core.c
- tests/check-uefi.c
- tests/harness.c
- tests/harness.h
The lack of kernel modules during install isn't necessarily fatal, and
some kernel configurations might be without modules entirely. Notably,
given that kernel modules are to be marked as resident on disk, even if
we have multiple packages compromising a kernel and separate modules, those
old modules will be removed at the time of the kernel change, and at no
other time, ensuring an atomic update.
This resolves #67.
> kernel: Allow lack of modules to be non-fatal

- configure.ac
- src/bootman/kernel.c
Two issues minor issues addressed. One is to get rid of build-time warning when archiving static libraries, the other one is incorrect comparison (forgotten dereference of a `char *`).
> Minor code cleanup

- src/cli/ops/timeout.c
Fix error messages, including a misspelling, and inconsistent use of periods within individual messages.
> Fix spelling, punctuation

- src/bootloaders/bootloader.h
- src/bootloaders/shim-systemd.c
- src/bootloaders/systemd-class.c
- src/bootloaders/systemd-class.h
- src/bootman/kernel.c
- tests/harness.c
Refactor the API slightly to reflect the intended use of
get_kernel_destination() function of the bootloader.
Fix plain memory management issues.
> Fix mem mgmt issues introduced by shim-systemd.

- .travis.yml
clang-format changes its output too much between versions to block
commits so go back to users being on their own for format following
the style rules.
> Remove clang-format use from travis

- src/bootloaders/systemd-class.c
- tests/check-uefi.c
- tests/harness.c
kernel.c no longer creates any layout, but systemd-class was not
creating/ensuring kernel target directory either. This fixes the issue.
Also, tests are fixed to use proper ESP standard names throughout.
> Fix kernel destination dir in systemd-boot.

- src/bootloaders/shim-systemd.c
- src/bootloaders/systemd-class.c
- tests/check-uefi.c
- tests/harness.c
- tests/harness.h
Both systemd-class and shim-systemd are fixed in separate commits.
Addresses the concerns raised in #88.
CC: @bryteise, @ikeydoherty
> Fixes case-intolerance in file names. Restores divergent names in tests.

- .gitmodules
- src/bootloaders/shim-systemd.c
- src/bootman/kernel.c
This initial change makes sure our codebase is more portable and doesn't depend too much on GNUisms like `#include <linux...`.
>  Portability support

- src/cli/main.c
When clr-boot-manager (CBM) is forked/exec'd via swupd-client, file
descriptor leak checks are performed first by CBM, and then by
swupd-client.
However, not all file descriptors opened by swupd-client will be closed
during the exec of CBM, leading to CBM falsely reporting leaks for file
descriptors inherited from the parent process. In cases when CBM reports
valid leaks, swupd-client will later report them as well, making the CBM
reports extraneous.
Arguably, swupd-client should try to mark its open file descriptors
O_CLOEXEC, but at least one of the descriptors is managed by libcurl,
and no API exists to set O_CLOEXEC on it (as far as I know).
So, for now, remove the file descriptor leak here. Perhaps reintroduce
it later when more testing is implemented to ensure that relevant file …
> Remove file descriptor leak check

- man/clr-boot-manager.1.in
- man/meson.build
Update man page to describe the use of the kernel configuration files
that can be modified by the system administrator to set the kernel
commandline.
> Add documentation to man page for kernel configuration

- .travis.yml
- meson.build
- meson_options.txt
- src/bootloaders/grub2.c
- src/bootloaders/syslinux.c
- src/bootloaders/systemd-class.c
- src/bootman/bootman.c
- src/bootman/bootman.h
- src/bootman/bootman_private.h
- src/bootman/update.c
- src/cli/ops/update.c
- tests/check-uefi.c
- tests/harness.c
- tests/harness.h
add suport for initrds without kernel dependencies in /usr/lib/initrd.d
just for systemd-boot at the moment
Signed-off-by: Josue David Hernandez <josue.d.hernandez.gutierrez@intel.com>
> clr-boot-manager: add support initrd no kernel dep

- src/lib/probe.c
Signed-off-by: Josue David Hernandez <josue.d.hernandez.gutierrez@intel.com>
> clr-boot-manager: add support for non-lvm root encryption

- src/bootman/kernel.c
In practice, the filename limit was overly small, this change allows
us to better describe the content of some kernels currently in use.
Signed-off-by: Murilo Belluzzo <murilo.belluzzo@intel.com>
> Increase maximum size of 'type' field

- src/bootloaders/shim-systemd.c
- src/lib/bootvar.c
When there is an issue with efivars do not fail the entire update
operation. Since the kernel and bootloader can still be successfully
updated and the bios can manually be updated to use the installed
bootloader, the efivar update is non-fatal. The operation being
treated as fatal could prevent update content from getting provisioned
to the EFI partition which is worse than not setting the bios
correctly for booting the updated system.
As part of this change add an error message to warn users they may
need to update their bios to select their desired boot option.
> Do not fail an update on efivar creation failure

- man/clr-boot-manager.1.in
- src/lib/cmdline.c
- src/lib/os-release.c
- src/lib/util.c
- src/lib/util.h
- tests/check-cmdline.c
- tests/data/cmdline_delete_all/etc/kernel/cmdline-removal.d/comments.conf
- tests/data/cmdline_delete_all/etc/kernel/cmdline-removal.d/mangledmess.conf
- tests/data/cmdline_delete_all/etc/kernel/cmdline-removal.d/multi.conf
- tests/data/cmdline_delete_all/etc/kernel/cmdline-removal.d/oneline.conf
- tests/data/cmdline_delete_all/usr/share/kernel/cmdline.d/full.conf
- tests/data/cmdline_delete_ends/etc/kernel/cmdline-removal.d/ends.conf
- tests/data/cmdline_delete_ends/usr/share/kernel/cmdline.d/full.conf
- tests/data/cmdline_delete_middle/etc/kernel/cmdline-removal.d/comments.conf
- tests/data/cmdline_delete_middle/etc/kernel/cmdline-removal.d/mangledmess.conf
- tests/data/cmdline_delete_middle/etc/kernel/cmdline-removal.d/multi.conf
- tests/data/cmdline_delete_middle/etc/kernel/cmdline-removal.d/oneline.conf
- tests/data/cmdline_delete_middle/usr/share/kernel/cmdline.d/full.conf
Add the ability for clr-boot-manager to handle removing content from
the kernel commandline. The removal configuration files are formatted
exactly the same as the add configuration files. The matches are done
line-by-line so that:
"option-a option-b"
in a removal file would only delete exactly that string unlike:
"option-a
option-b"
in a removal file which would try to remove "option-a" and "option-b"
separately.
> Enable commandline removal configuration files

- man/clr-boot-manager.1.in
- man/meson.build
Add details to how the files should be structured and where the vendor
configuration files are that the user configuration files can
override.
> Improve documentation of the kernel commandline addition files

- src/cli/ops/update.c
Exit early without error when the path to distro content kernel files
does not exist. This prevents code that expects the kernels to exist
from failing with unexpected errors.
> Only attempt update when kernel path exists

- man/clr-boot-manager.1.in
This is nothing major, but I saw that the link inside the man page was using unencrypted http so I figured I would send a little PR to fix it. With all the talk about security online and stuff we should try to use https as much as possible. :)
> Let's use https for security reasons

- src/lib/util.h
The DECLARE_OOM macro didn't add a newline at the end leading to
potentially confusing output.
> Fix output of DECLARE_OOM macro

- src/bootman/bootman.h
- src/bootman/kernel.c
- src/cli/ops/update.c
Previous code would try and find informatin about the given root even
when the kernel dir under the root did not exist causing unhelpful
errors. Update to check if the kernel dir exists before probing the
given root and exit if it does not.
> Do not attempt an update without a kernel dir

- data/completions/zsh/_clr-boot-manager
Added completions for sub-commands, including
- Path completion if a sub-command accept `--path=` option
- Shows a list of kernels for `set-kernel` sub-command, where it searches for
kernels under `/usr/lib/kernel` by default, while prepends the option arg of
`--path` if it's given. If the user specified a path manually, instead of
using file path completion, and that path doesn't exist, warns user.
- Reminds the user to input a integer value for `set-timeout`
sub-command
- Adds all sub-commands to completion menu as argument to `help` sub-command
> zsh-completion: Improved

- data/completions/bash/clr-boot-manager.in
- data/completions/zsh/_clr-boot-manager.in
It was wrongly described as `Software Updater - autocompletion script`, and it's changed to
`Kernel & Boot Loader Management - autocompletion script`.
> completions: Minor fix on comments

- src/bootman/sysconfig.c
Either boot_device or legacy_boot needs to be maintained, thus
the unused one should be properly deallocated.
> bootman: deallocate boot device strings

- meson.build
- meson_options.txt
- src/lib/bootvar.c
With that each vendor can create a more meaningful uefi menu entry if provided on
build time.
> efi: add a entry_label argument

- src/cli/cli.c
- src/cli/cli.h
- src/cli/main.c
A few house keeping on the clr-boot-manager's cli.
* Remove dead code
* added common code to deal with default opts and showing'em on the help display in a generic way;
> Help: add a generic way of dealing with default opts

- src/cli/ops/timeout.c
Currently when the user calls the set-timeout command that change
will only be applied after calling update command, with this patch
we internally call update command.
> set-timeout: make sure to apply the changes

- man/clr-boot-manager.1.in
We're missing man page documentation to the recent user initrd freestanding
file.
> man: add /etc/kernel/initrd.d documentation

- meson.build
- meson_options.txt
- src/bootman/bootman.c
- src/meson.build
We would like to disable grub2 in scenarios/configurations where we
know we won't ever use/need it.
> grub2: make it optional

- src/cli/ops/timeout.c
- src/cli/ops/update.c
- src/cli/ops/update.h
Avoid parsing flags, allocating BootManager twice when calling update
from time out command.
> timeout/update: don't allocate/free manager twice

- src/lib/files.c
We've found some cases where the path to LoaderDevicePartUUID will have
some "virtual" entries containing some "garbage" in the path. This patch
makes sure we always match only the right formatted ones.
Fixes: #199
> get_boot_device: fix efi loader path matching

- src/cli/ops/timeout.c
- src/cli/ops/update.c
- src/cli/ops/update.h
With the commit 512323d we started ignoring the --path flag therefore breaking image
mode use cases. This patch brings back --path flag.
> fix regression introduced by 512323d

- src/bootloaders/extlinux.c
- src/bootloaders/syslinux.c
If we don't find the boot partition then we warn the user exit, currently we
segfault.
> legacy boot

- src/bootloaders/extlinux.c
- src/bootloaders/syslinux.c
- src/lib/files.c
- src/lib/files.h
+ syslinux was broken due an mtool dependency issue, we better eliminate the dependency and use syslinux-nomtools - bonus point we reduce the footprint (beneficial to small images).
+ sanity check configuration file before comparing previous versions and avoid segfaulting.
> Fix legacy boot

- .gitignore
- scripts/mkrelease.sh
Make our life easier, put together all the required steps before cutting a new
release instead of having to remember it all.
Change the VERSION file, create the release commit and tag. Bonus point added a
--help flag so we can easily remember how this script works.
> mkrelease: put together all the required steps before release

- src/bootloaders/systemd-class.c
With recent systemd changes cbm use cases will break if we don't add ".conf" to the
loader.conf default entry configuration.
> systemd compatibility

- src/lib/probe.c
Software RAID does not see PARTUUID, so only use UUID.
Part of the enablement for the clr-installer to support software RAID for the / (root) file system.
> probe: Add check for Software RAID root device

- src/bootloaders/syslinux-common.c
Make sure we honor users timeout configuration propagating it to config file when
running update command.
Closes #229 #221
> syslinux/extlinux: add timeout support

- src/lib/blkid_stub.c
- src/lib/blkid_stub.h
- src/lib/files.c
- src/lib/files.h
- src/lib/probe.c
- src/lib/probe.h
- src/lib/system_stub.c
- src/lib/system_stub.h
- tests/blkid-harness.h
- tests/check-legacy.c
- tests/check-probe.c
- tests/check-select-bootloader.c
- tests/check-syslinux.c
- tests/system-harness.h
Calling stat() on some filesystems, like Btrfs,
results in a dev_t with no relation to the backing device(s),
and subsequent failure to detect the root fs.
Add support such filesystems by retrieving the block device from
`/proc/self/mounts` and working on from there.
Resolves #61, #182 and #193.
> Add support for non-ext filesystems

- man/clr-boot-manager.1.in
- man/meson.build
- src/bootloaders/grub2.c
- src/bootloaders/syslinux-common.c
- src/bootloaders/systemd-class.c
- src/bootman/bootman.c
- src/bootman/bootman.h
- src/bootman/bootman_private.h
- tests/check-uefi.c
Microcode early loading only works on the first initrd passed to the kernel, so make sure the first one we specify in the bootloader config is actually a microcode initrd.
> Make sure microcode initrd is loaded first

- data/completions/bash/clr-boot-manager.in
- data/completions/zsh/_clr-boot-manager.in
- man/clr-boot-manager.1.in
- src/bootman/bootman.c
- src/bootman/bootman.h
- src/cli/main.c
- src/cli/ops/kernels.c
- src/cli/ops/kernels.h
In some cases users will want to remove kernels from their systems outside an update workflow. This is fairly painful to do manually so add a command to handle the operation which removes both the /boot data and configuration files as well as the /usr data.
The default symlink for a kernel type will remain as this is something that the update mechanism should be in control of and figuring out what would be the fallback is out of cbm's scope.
Signed-off-by: William Douglas <william.douglas@intel.com>
> Add remove-kernel command

- src/bootman/bootman.c
If boot_manager_set_default_kernel() is called with a NULL kernel target, explicitly return false.
> Prevent segfault in boot_manager_set_default_kernel

- src/cli/main.c
When running `get-timeout` without root, it will fail with an error ('failed to create a new libblkid probe'). Require root permissions for the `get-timeout` subcommand to clarify this.
> Require root for `get-timeout`

- src/lib/probe.c
As noted in #134, I believe the order is the wrong way round.
I have tested this on Solus with Btrfs on LUKS, and Btrfs on LVM on LUKS. I was unable to test this on a clean Clear Linux or Solus install, as both failed to install with disk encryption in a (BIOS) VM.
Resolves #134
> Fix LUKS glob order

- src/bootloaders/shim-systemd.c
The Mok Management EFI executable (generally mmx64.efi) is needed in a few cases (when secure boot is enabled):
- When using a third-party shim requiring you to enroll your own cert on first boot
- When using a custom kernel or bootloader allowing the user the enroll the hash of it in order to boot
According to the layout comment on the top of the file this should already be expected to be on the ESP, fix that.
> shim-systemd: Install & update the Mok Management executable on the ESP
