clearlinux/clr-boot-manager

src/lib/probe.c
src/lib/probe.h

Gave you an easy one for a change :)

lib/probe: Add missing modelines

---

README.md

Add language under requirements to specify more precisely what
clr-boot-manager's purpose is regarding boot artifacts and system boot
flow.
Attempts to resolve #52

Update use case description in README

---

src/bootman/kernel.c
tests/check-uefi.c

Prior to this change, the kernel and initrd paths were not using the
namespace directory during kernel removal, leading to assets being left
on the disk and filling up the ESP with junk that could not be reclaimed.
This change introduces the simple fix, as well as the UEFI specific test
to ensure that the files are being removed.

bootman: Ensure that we use the full namespace for EFI assets

---

src/bootman/update.c

Fix typo in error message

---

HACKING

Add details for if statement bracket use and function and variable
names.

Update code syle documentation

---

src/bootloaders/shim-systemd.c

The layout has changed to get rid of `/EFI/<KERNEL_NAMESPACE>/kernel` directory. kernels are now copied to `/EFI/<KERNEL_NAMESPACE>`, at the same level as the bootloaders.
This coincides with the layout used by `systemd-class` in what relates to kernel target directory.

Change layout to get rid of subdirectory for kernels in shim-systemd.

---

src/bootman/bootman.h
src/bootman/kernel.c

Cleanup /usr/lib/vmlinux-(version) files in /usr/lib/kernel.
Fixes #114

Cleanup vmlinux file

---

man/clr-boot-manager.1.in
src/bootloaders/bootloader.h
src/bootloaders/grub2.c
src/bootloaders/shim-systemd.c
src/bootloaders/syslinux.c
src/bootloaders/systemd-boot.c
src/bootloaders/systemd-class.c
src/bootloaders/systemd-class.h
src/bootman/bootman.c
src/bootman/bootman.h
src/bootman/kernel.c
src/bootman/update.c
src/cli/main.c
src/cli/ops/kernels.c
src/cli/ops/kernels.h
src/meson.build
tests/check-uefi.c

Enable listing available kernels and setting the default kernel to be
used to boot.
Also fixes a buffer overflow.

Add support for viewing and changing kernels

---

src/bootman/bootman.h
src/bootman/kernel.c

Fixes #139.
- Fix size check.
- Increase max len from 15 to 31.
@bryteise

Fix kernel type handling/size.

---

src/bootman/update.c

In some cases the bootloader update will not impact the kernel update,
usually when another tool like syslinux is used which may fail
independently of the file copies the kernel update will need. Since
the kernel update may still succeed always attempt it to avoid cases
where the kernel becomes stale as it is more likely to need updates
than the bootloader.

Attempt kernel update even if bootloader update fails

---

src/bootman/bootman.c

This should fix issue #152 and #148

Fix "double free or corruption (!prev)" error

---

src/bootloaders/extlinux.c
src/bootman/bootman.c
src/bootman/bootman.h
src/bootman/bootman_private.h
src/bootman/kernel.c
src/bootman/sysconfig.c
src/lib/files.c
src/lib/files.h
src/lib/log.h
tests/check-core.c
tests/check-grub2.c
tests/check-legacy.c
tests/check-probe.c
tests/check-select-bootloader.c
tests/check-syslinux.c
tests/check-uefi.c

+ split the root inspect into native and image - that way we can better visualize how the wanted mask is composed
+ add some cosmetic changes

For review

---

.github/workflows/main.yml
README.md

Preparing to migrate from travis to github actions.

Add github actions workflow

---

.github/workflows/main.yml

It seems that without pull_request event the pull request will not
get actions triggered.

add pull_request event to actions

---

man/clr-boot-manager.1.in
src/bootloaders/shim-systemd.c
src/bootman/bootman.c
src/bootman/bootman.h
src/bootman/bootman_private.h
src/cli/cli.c
src/cli/cli.h
src/cli/ops/kernels.c
src/cli/ops/timeout.c
src/cli/ops/update.c

This PR implements #188 issue.

Skip efi vars update

---

meson.build
meson_options.txt
src/bootman/bootman.c
src/bootman/bootman_private.h
src/lib/log.h

This pull request implements the features requested on #187.

User initrd dir

---

README.md

Remove whitespace in README

---

src/bootloaders/extlinux.c

Make sure extlinux is consistent with syslinux and mark the boot partition as legacy
bios bootable.

extlinux: mark boot partition as legacy bios bootable

---

src/bootloaders/extlinux.c
src/bootloaders/syslinux-common.c
src/bootloaders/syslinux-common.h
src/bootloaders/syslinux.c
src/bootman/bootman.c
src/bootman/bootman.h
src/bootman/bootman_private.h
src/meson.build

+ revamps the extlinux/syslinux implementation to unify the common code and remove duplication
+ fix set-kernel for legacy bios mode (namely extlinux/syslinux implementation)
+ fix list-kernels for legacy bios mode
fixes: #217 #211

Extlinux syslinux fixes

---

data/completions/bash/clr-boot-manager.in
data/completions/zsh/_clr-boot-manager.in

- Added `--image` and `--no-efi-update` flags
- Minor changes in zsh script.

completions: Update bash and zsh completions

---

src/lib/util.h

OOM: add file and function name to OOM message

---

src/bootman/bootman.c
src/bootman/sysconfig.c
src/lib/files.c
src/lib/probe.c
src/lib/probe.h
tests/check-legacy.c

Fixes https://github.com/clearlinux/distribution/issues/2636

Fixup rootfs detection fallback

---

how-to-make-a-release
scripts/mkrelease.sh

Signed-off-by: William Douglas <william.douglas@intel.com>

Add release process document
